daemon:
    processName: gpioMon
    pidPath: /var/run
    host: localhost
    port: 8282
    logFile: logs/process.log
#    logFile: /media/dataStorage/logs/gpioMon/process.log

readIntervals:
    temperature: 30
    door: 0.5

doorMonitor:
    gpioPin: 3
    logFile: logs/doorState.log
#    logFile: /media/dataStorage/logs/gpioMon/doorState.log

temperatureMonitor:
    logFile: logs/temperature.log
#    logFile: /media/dataStorage/logs/gpioMon/temperature.log
